--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/BetterItemID
build-by-default: true
branches:
- PM4
projects:
  BetterItemID:
    path: ""
    icon: icon-betteritemid.png
    libs:
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.0.1
    lint:
      phpstan: false
...
