--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/BetterItemID
build-by-default: true
branches:
- PM4
projects:
  BetterItemID:
    path: ""
    icon: icon-betteritemid.png
    lint:
      phpstan: false
...
