name: BetterItemID
main: fernanACM\BetterItemID\ItemID
version: 1.0.0
api: 4.0.0
author: fernanACM
description: The best ItemID for PocketMine-MP 4.0 servers. Special use for builders.
website: https://github.com/fernanACM

permissions:
  betteritemid.cmd.acm:
    default: op
    description: Use /betteritemid
