name: BetterItemID
main: fernanACM\BetterItemID\ItemID
version: 3.0.0
api: 5.3.0
author: fernanACM
description: The best ItemID for PocketMine-MP 5.0 servers. Special use for builders.
website: https://github.com/fernanACM

permissions:
  betteritemid.cmd.acm:
    default: op
    description: Use /betteritemid
  betteritemid.use.acm:
    default: op
    description: Use blockinfo